print("Getting to know you!")
print()
name = input("What's your name? ")
print("Nice to meet you", name + "!")
print()
favorite_food = input("What's your favorite food? ")
print(favorite_food + "!", "you got me hungry!")
print()
favorite_music = input("What's your favorite musical genre? ")
print(favorite_music + ",", "is so cool!")
print()
place = input("And lastly, where do you live? ")
print(place + "?", "I'd like to go there someday!")
print()
print("Thanks for sharing this with me", name + "!",
      "I'll never forget that...")
print()
print("Your name is", name + ",", "your favorite food is", favorite_food + ",",
      "your favorite musical genre is", favorite_music + ",",
      "and you live in ", place + "!")